---
# tasks file for kubernetes

#- import_tasks: configure_kubernetes_servers.yml

<<<<<<< HEAD
- import_tasks: configure_aws_kubernetes_server.yaml
=======
- import_tasks: configure_localhost_kubernetes_server.yaml  
>>>>>>> 7141c9c (Updates)
