---
- name: Configuring Kubernetes Cluster
  hosts: Cluster
  tasks:
  - name: Configuring Kubernetes Master and Worker Server (Updating Servers)
    yum:
      name: '*'
      state: latest

  - name: Remove the Docker package
    yum:
      name: "{{ Docker }}"
      state: absent
    vars:
      Docker:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-logrotate
      - docker-engine

  - name: Install a list of packages using  variable
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - firewalld
      - yum-utils
      - tree
      - mlocate
      - curl
      - vim
      - wget  

  - name: Disabling Firewalld
    raw: systemctl enable --now firewalld && systemctl disable --now firewalld

      #- name: Disabling SELINUX
      # shell: setenforce 0 && sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
  
  - name: Adding Docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Installing Docker
    shell: yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

  - name: Enabling/Start Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Disable swap and new files
    shell: sed -i '/swap/d' /etc/fstab && swapoff -a && touch /etc/sysctl.d/kubernetes.conf && touch /etc/yum.repos.d/kubernetes.repo && touch /etc/modules-load.d/k8s.conf

  - name: Adding configurations to kernel modules
    blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter

  - name: Enable transparent masquerading and facilitate Virtual Extensible LAN (VxLAN) traffic for communication between Kubernetes pods across the cluster
    raw: modprobe overlay && modprobe br_netfilter

  - name: Adding configurations to Sysctl
    blockinfile:
      path: /etc/sysctl.d/kubernetes.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-iptables = 1

  - name: Reactivating Sysctl
    raw: sysctl --system

    
  - name: Adding kubernetes repo
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl

  - name: Installing Kubernetes
    shell: yum install -y kubelet-1.24.0-0.x86_64 kubeadm-1.24.0-0.x86_64 kubectl-1.24.0-0.x86_64 kubernetes-cni-1.2.0-0.x86_64 --disableexcludes=kubernetes

  - name: Enabling/Start Kubelet
    service:
      name: kubelet
      state: started
      enabled: yes
