# The below is the aws_ec2 plugin specified in the /etc/ansible/ansible.cfg
#plugin: amazon.aws.aws_ec2
plugin: aws_ec2
aws_profile: default
regions:
  - us-east-1 

hostnames:
  - ip-address

#keyed_groups:
#  - prefix: arch
#    key: architecture  

#keyed_groups:
#  - prefix: az
#    key: placement.availability_zone

groups:
  Kubernetes_Master: "'Kubernetes_Master' in tags.Name" 
  Kubernetes_Worker: "'Kubernetes_Worker' in tags.Name"
  NFS_Server: "'NFS_Server' in tags.Name"
  Bastion_Server: "'Bastion_Server' in tags.Name"  
